version: '3'
services:
  postgresql:
    image: postgres:latest
    container_name: neo_otaku_word_postgres
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    user: $POSTGRES_USER