 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/otaku_words", type: :request do
  # OtakuWord. As you add validations to OtakuWord, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      OtakuWord.create! valid_attributes
      get otaku_words_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      otaku_word = OtakuWord.create! valid_attributes
      get otaku_word_url(otaku_word)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_otaku_word_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      otaku_word = OtakuWord.create! valid_attributes
      get edit_otaku_word_url(otaku_word)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new OtakuWord" do
        expect {
          post otaku_words_url, params: { otaku_word: valid_attributes }
        }.to change(OtakuWord, :count).by(1)
      end

      it "redirects to the created otaku_word" do
        post otaku_words_url, params: { otaku_word: valid_attributes }
        expect(response).to redirect_to(otaku_word_url(OtakuWord.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new OtakuWord" do
        expect {
          post otaku_words_url, params: { otaku_word: invalid_attributes }
        }.to change(OtakuWord, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post otaku_words_url, params: { otaku_word: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested otaku_word" do
        otaku_word = OtakuWord.create! valid_attributes
        patch otaku_word_url(otaku_word), params: { otaku_word: new_attributes }
        otaku_word.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the otaku_word" do
        otaku_word = OtakuWord.create! valid_attributes
        patch otaku_word_url(otaku_word), params: { otaku_word: new_attributes }
        otaku_word.reload
        expect(response).to redirect_to(otaku_word_url(otaku_word))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        otaku_word = OtakuWord.create! valid_attributes
        patch otaku_word_url(otaku_word), params: { otaku_word: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested otaku_word" do
      otaku_word = OtakuWord.create! valid_attributes
      expect {
        delete otaku_word_url(otaku_word)
      }.to change(OtakuWord, :count).by(-1)
    end

    it "redirects to the otaku_words list" do
      otaku_word = OtakuWord.create! valid_attributes
      delete otaku_word_url(otaku_word)
      expect(response).to redirect_to(otaku_words_url)
    end
  end
end
